# Generated by Django 4.2.3 on 2023-08-02 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manage_server", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="managedpcuser",
            name="managed_pc",
        ),
        migrations.CreateModel(
            name="ManagedPCUserRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="last update"),
                ),
                (
                    "managed_pc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manage_server.managedpc",
                    ),
                ),
                (
                    "managed_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manage_server.managedpcuser",
                    ),
                ),
            ],
        ),
    ]
